require 'ostruct'
require 'renee_bindings/adapters/base_adapter'
require 'renee_bindings/adapters/primitive_adapter'
require 'renee_bindings/adapters/json_adapter'
require 'renee_bindings/adapters/ruby_adapter'
